#' Compute Wind Power
#'
#' power of wind turbine
#' This function computes power in watts and kinetic energy in Joules
#' generated by a wind turbine given its blade length and wind speeds
#' @param coefficient_of_performance is the efficiency of the windmill (percent). default is 0.45
#' @param pi is 22/7
#' @param air density (kg/m^3) default is 2360
#' @param blade_length in m
#' @param windspeed is the speed of the wind blowing in m/s
#' @examples compute_wind_power(20,30)
#' @author Nadine, Adele, and Hannah


compute_wind_power <- function (blade_length, wind_speed, CP=0.45, pi= 22/7, mass=2360) {

  ## stop the function if blade length is 0 or negative:
  if(blade_length <= 0){
    stop("Please check your Blade Length and Try Again")
  }

  ## stop the function if wind speed is negative, otherwise, proceed
  wind = ifelse(wind_speed < 0, stop("Please check your Wind Speed and Try Again"), wind_speed)


  power = 0.5 * CP * pi * (blade_length)^2 * (wind)^3 ##calculate power

  inertia <- ((blade_length^2)*mass) ##caculate moment of inertia


  KE <- (0.5*inertia*wind^2) ## calculate kinetic energy

  results <- c(KE, power) ## make a vector containing KE and power

  return(results) ##return vector

}




